"""empty message

Revision ID: 08db34892750
Revises: 
Create Date: 2025-11-04 21:30:36.563927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08db34892750'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('idade', sa.String(length=10), nullable=True),
    sa.Column('urgencia', sa.String(length=20), nullable=True),
    sa.Column('convenio', sa.String(length=50), nullable=True),
    sa.Column('hora_chegada', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paciente')
    op.drop_table('cliente')
    # ### end Alembic commands ###
