"""Create tables

Revision ID: 624ad5d32df7
Revises: 
Create Date: 2025-10-31 23:28:44.546600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624ad5d32df7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('codigo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cidade', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('codigo'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('urgencia', sa.String(length=20), nullable=True),
    sa.Column('convenio', sa.String(length=10), nullable=True),
    sa.Column('hora', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paciente')
    op.drop_table('cliente')
    # ### end Alembic commands ###
