"""add rg cpf paciente

Revision ID: 76a9f606824f
Revises: 08db34892750
Create Date: 2025-11-04 22:10:47.138172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76a9f606824f'
down_revision = '08db34892750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rg', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cpf', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_column('cpf')
        batch_op.drop_column('rg')

    # ### end Alembic commands ###
